##########################################################
## THIS FILE WAS AUTO GENERATED BY THE BINDWRITER TOOL  ##
##                                                      ##
## ANY ALTERATIONS OF THIS FILES CONTENTS MAY CAUSE     ##
## UNEXPECTED BEHAVIOUR                                 ##
##########################################################
## File Usage: Import DLL and wrap its exposed          ##
## functions and classes                                ##
##########################################################


"""python Wrapper for the C++ example lib"""

## Util ##

def to_cint(i):
	    return ctypes.c_int(i)
def to_cstr(fmt):
	    return bytes(fmt, "utf8")

import ctypes
Example = ctypes.CDLL('C:/Users/seawa/Desktop/PyBinding/Examplecpp/bin/Debug/example_cpp.dll')


## FUNC DEFS ##
''' Func InitGLFW '''
def InitGLFW():
	"""Initialize GLFW"""
	Example.InitGLFW()
''' Func Main '''
Example.Main.argtypes = [ctypes.c_char_p]
def Main(c_char_pA):
	 
	Example.Main(c_char_pA)

## MEMBER FUNC DEFS ##
''' Func PyCreate_BasicClass '''
Example.PyCreate_BasicClass.restype = ctypes.c_void_p
''' Func BasicClass_WhatIs '''
Example.BasicClass_WhatIs.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int]
''' Func PyDestroy_BasicClass '''
Example.PyDestroy_BasicClass.argtypes = [ctypes.c_void_p]

## CLASS DEFS ##
class BasicClass:
	def __init__(self):
		self.cInstance = Example.PyCreate_BasicClass()

	def WhatIs(self, c_intA, c_intB):
		"""prints the sum of the two ints"""
		Example.BasicClass_WhatIs(self.cInstance, c_intA, c_intB)

	def __del__(self):
		Example.PyDestroy_BasicClass(self.cInstance)

	